name: musclepaste
favicon: null
layout_spectrum: 0.40842637014290906
typography_spectrum: 0.570430655213565
title: Muscle Paste - Sport Nutrition Made Easy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70483216-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7011258456578217
  lightness: 0.32646562577242233
  saturation: 0.11562433597091837
  rhythmicContrast: 0.08562717447484258
purpose:
  - name: null
    item: null
    url: null
